---
title: Potências Médias - projeto de pesquisa
type: ARTICLE TEMPLATE
author:
  - name: M. Galdino
    affil: a
    email: mgaldino@usp.br
affiliation:
  - num: a
    address: |
      Political Science Department, Universidade de são Paulo, Brazil.
bibliography: Middle-Powers-bib.bib
appendix: appendix.tex
abstract: |
  O conceito de potências médias, apesar de sua prevalência na literatura de Relações Internacionais (RI), enfrenta um desafio crítico de ambiguidade conceitual que limita sua utilidade analítica. Esta pesquisa visa abordar esse desafio propondo um novo arcabouço teórico que integra a teoria dos jogos não cooperativa, especificamente através da adaptação dos conceitos de estratégias complementares e substitutas. Ao fazer isso, o projeto tem como objetivo superar as divisões teóricas existentes e promover uma compreensão mais precisa e abrangente das potências médias. Tradicionalmente, a RI concentrou-se na teoria do comportamento das grandes potências, negligenciando uma teoria inclusiva que explique o comportamento de estados de diferentes magnitudes. Este estudo argumenta pela necessidade de uma teoria do comportamento estatal que englobe não apenas as grandes potências, mas também as médias e pequenas, oferecendo uma maneira empírica de diferenciar esses grupos de países. Ao unificar as variáveis explicativas relacionadas ao poder, comportamento e identidade dos estados, propomos um caminho para uma validação empírica robusta, estabelecendo um programa de pesquisa progressivo no sentido Lakatos. Além de sua contribuição teórica, este projeto delineia um desenho de pesquisa empírica, priorizando o estudo de cabos diplomáticos como fontes primárias. Essas fontes são consideradas essenciais para testar as hipóteses derivadas de nossa abordagem teórica, possibilitando uma avaliação detalhada das estratégias adotadas pelas potências médias no cenário internacional. Assim, o projeto não apenas promete clarificar a categorização de potências médias, mas também fornece uma base para futuras investigações empíricas neste campo, contribuindo significativamente para a literatura existente e oferecendo novas ferramentas analíticas para pesquisadores e formuladores de políticas.

keywords: |
  Potências Médias; Teoria dos Jogos; Estratégias Complementares; Estratégias Substitutas; Cabos Diplomáticos;
header-includes: |
  \usepackage{hyperref}
  \usepackage[utf8]{inputenc}
  \def\tightlist{}
output: rticles::tf_article
---

# Introdução

A Teoria das Potências Médias, desde seu início (cf. @chaudhuri_1969; @holbraad_71), enfrentou problemas de clareza analítica. A dificuldade em conceituar quem seriam as potências médias, seja por alguma medida objetiva de poder (combinando um ou mais indicadores) ou por seu comportamento, é reveladora dessa confusão analítica. A despeito disso, a literatura continua a usar o conceito, variando na forma de defini-lo e operacionalizá-lo empiricamente, assim como nas várias tentativas de resolver os problemas conceituais.

A concepção mais tradicional de potência média é baseada na posição que os estados ocupam no sistema internacional (por exemplo, @holbraad_84; @cooper_etal_93; @shin_12). Assim, países com capacidades médias ou medianas teriam um comportamento de política externa diferente ou previsível em relação a estados com maior ou menor capacidade. Essa diferenciação pode se dar tanto pela formação de interesses distintos quanto pelo estilo ou estratégia de atuação na esfera internacional (cf. @cooper_11 para uma revisão da literatura). No entanto, isso não é suficiente para operacionalizar o conceito de maneira consistente, uma vez que não há clareza sobre qual medida de capacidade deve ser usada (seja ela militar, econômica, diplomática ou uma combinação dessas e de outras variáveis), a posição relativa pode mudar dependendo da região geográfica considerada e a inclusão de variáveis como participação em alianças, ao modificar a medida de poder, acaba trazendo confusão analítica ao conceito (@cooper_11). O resultado dessa confusão é a inexistência de uma lista definida, no tempo e espaço, de quais países seriam potências médias, o que torna inviável testar se, de fato, há um comportamento distintivo na política externa desses países.

Em segundo lugar, há teorias focadas no comportamento desses estados. O que seria distintivo das potências médias seria seu comportamento, tal como a adesão ao multilateralismo, a tentativa de agir como “bom cidadão”, a capacidade de atuar como mediador de conflitos, etc. (@schiavon_dominguez_16; @stephen_13; @welsh_04). 

O problema óbvio dessa abordagem é a impossibilidade de explicar comportamento com base em uma categorização do comportamento devido à óbvia circularidade. Além disso, essa abordagem tampouco contribuiu, ao menos, para observar um padrão de comportamento dos países tradicionalmente concebidos como potências médias. Alguns estudos combinam capacidades e comportamento para classificar os países, mas isso não resolve o problema de circularidade (@cooper_11).

Por fim, mais recentemente, tem havido tentativas de conceituar potência média a partir da identidade dos estados, em particular aqueles que se autodefinem como potências médias (@hynek_07; @gecelovsky_09; @debhal_23).

Esse espectro conceitual sugere uma continuidade com a tradição da RI no estudo das grandes potências. Tradicionalmente, a RI focou em uma teoria do comportamento das grandes potências, deixando um vazio analítico sobre o comportamento estatal além dessas. A categorização qualitativa de "grande potência" ou “superpotência” indica que outras categorias, como as "potências médias", podem ser analiticamente úteis, embora a sua utilidade ainda seja um ponto de debate intenso.

Ante a complexidade desse cenário, parece claro que, para redescobrir a utilidade analítica do conceito de potências médias, é necessário um trabalho teórico e empírico de grandes proporções. Do lado teórico, parece-nos claro que qualquer que seja o marcador ou marcadores que distingam potências médias, essas variáveis precisam estar relacionadas também ao comportamento dos estados de outros tamanhos. Isso sugere que a pesquisa empírica nessa área precisa ser comparativa e incluir não apenas as pretensas potências médias, mas também os países que estariam em outras categorias.

O presente trabalho, portanto, parte dessa ambição como horizonte de pesquisa. Por outro lado, este é um projeto laborioso e que exigirá esforço colaborativo para ser empreendido. Assim, o que apresentamos a seguir é nossa estratégia para um primeiro passo nessa direção, sem a pretensão de delinear o caminho todo a ser percorrido. Além de ser mais realista, parece-nos mais efetivo, na medida em que facilita a correção de rotas que o trabalho de pesquisa e as descobertas não antecipadas demandam.

No nível teórico, o presente trabalho propõe uma solução ancorada em uma adaptação dos conceitos de estratégias complementares e substitutas da teoria dos jogos não cooperativa. Esta abordagem promete superar a ambiguidade conceitual em torno das potências médias, unificando os comportamentos dos estados numa única teoria que explique a diferenciação entre os três grupos de países - grandes, médias e pequenas potências. Argumentamos que tal teoria, ao enfatizar a centralidade das relações entre estratégias dos países em diferentes arenas de conflito (se complementares ou substitutas), abre caminho para uma nova agenda de pesquisa empírica.

A perspectiva que adotamos aqui não é inteiramente nova, já que a interconexão entre jogos distintos e suas consequências nas decisões dos jogadores é um conceito que já foi explorado no campo das Relações Internacionais, particularmente na teoria de jogos de dois níveis de Putnam (1988) e suas subsequentes ampliações e aplicações. Entretanto, nosso framework se distingue ao aplicar-se a qualquer conexão entre jogos distintos, não apenas entre o nível doméstico e externo, proporcionando insights únicos sobre a dinâmica de estratégias complementares e substitutas.

Outra abordagem relacionada é a de "issue linkages" (Tollison & Willett, 1979), que embora compartilhe algumas semelhanças com nosso framework, difere na medida em que foca na construção de acordos multidimensionais que geram benefícios mútuos, sem necessariamente antecipar as complementaridades ou substitutibilidades estratégicas. Assim, embora haja precedentes, nossa abordagem teórica é pioneira no campo das relações internacionais.

Do ponto de vista empírico, pretendemos construir uma base de dados de cabos diplomáticos de países em perspectiva comparada, consistindo de países dos mais variados tamanhos. A recente proliferação das leis de acesso à informação e iniciativas de dados abertos mundo afora (@zuffova_20) possibilita que, finalmente, tal tarefa possa ser empreendida com boa chance de sucesso.

Este estudo busca, portanto, consolidar a teoria de potências médias como um programa de pesquisa progressivo, no sentido proposto por Lakatos, mediante a conexão de variáveis explicativas - sejam elas relativas a poder, comportamento ou identidade - com hipóteses causais testáveis empiricamente. 

A abordagem proposta oferece um caminho promissor para a superação dos desafios conceituais e metodológicos que têm caracterizado o estudo das potências médias até o momento. Por fim, pretendemos ilustrar essa perspectiva com um estudo de caso focado no Brasil e EUA, estudando os cabos diplomáticos disponíveis para ambos os países.

Nas próximas seções, desenvolvemos um pouco mais o arcabouço teórico, para ilustrar o tipo de teorização que será realizada, e, em seguida, apresentamos como se dará a pesquisa empírica no estudo de caso que pretendemos realizar.


# Modelo Teórico

Em um artigo seminal sobre a aplicação da teoria dos jogos à economia, @bulow_etal_85 introduziu a ideia de jogos com estratégias complementares ou substitutas. Considerando as estratégias como variáveis contínuas (e.g., nível de investimento), estratégias são ditas complementares se o aumento no nível de uma estratégia por um agente torna ótimo para outro agente aumentar o nível de sua própria estratégia. Matematicamente, isso ocorre quando a derivada parcial cruzada do payoff de um agente, em relação à sua estratégia e à do outro jogador, é positiva. Em contraste, estratégias são substitutas quando o aumento na estratégia de um agente leva o outro a reduzir a sua, evidenciado por uma derivada parcial cruzada negativa.

O exemplo arquetípico apresentado por @bulow_etal_1985 envolve dois mercados, $1$ e $2$, com demandas independentes onde a empresa $A$ monopoliza o primeiro mercado e compete com a empresa $B$ no segundo. Como os produtos de $A$ e $B$ no mercado $2$ são substitutos, o modelo de equilíbrio de Cournot demonstra que um comportamento mais agressivo de $A$ no mercado $1$ induz a empresa $B$ a ser menos agressiva no mercado $2$, evidenciando a substitutividade das estratégias.

Esse modelo tem implicações significativas ao ser transportado para o contexto das Relações Internacionais, sugerindo que o ganho de um estado $A$ derivado de uma mudança em um jogo $1$ é afetado pela sua posição em um jogo $B$, seja como grande potência (monopolista), potência média (oligopolista) ou pequena potência (competidor puro).

A aplicação deste arcabouço às Relações Internacionais permite discutir como grandes potências distinguem-se das potências médias pela capacidade de alterar os termos do jogo $1$, induzindo comportamentos específicos nos países envolvidos. Da mesma forma, potências médias podem adotar comportamentos de coalizões empreendedoras de norma (@ravenhill_2018), alterando exogenamente os custos para países em um jogo A, para induzir mudanças de comportamento em um jogo B.

Para ilustrar o potencial analítico desse arcabouço, propomos um esboço informal de dois jogos distintos, demonstrando como a presença de estratégias complementares ou substitutas explica certos comportamentos e auxilia na categorização dos tamanhos das potências.

Diferentemente da literatura existente, nossa abordagem torna a categorização de potência média dependente da estrutura da conectividade dos jogos. Assim, podemos clarificar a confusão conceitual presente na definição de potências médias na literatura, utilizando medidas de capacidade que influenciam a estrutura (complementar ou substituta) das estratégias, enquanto incorporamos variáveis contextuais (como a participação em alianças) e a identidade dos atores, na medida em que afetam suas preferências. Além disso, ao propor um mecanismo específico, podemos testar empiricamente as hipóteses derivadas dos modelos sem incorrer em circularidade argumentativa.


## Modelos de Estratégias Complementares e Substitutas

Considere um jogo entre dois estados, $A$ e $B$, disputando um território de valor $X = [0,1]$, conforme proposto por Fearon (1995). O estado $A$ prefere um resultado próximo de $1$, enquanto $B$ favorece um resultado próximo de $0$. Na negociação diplomática para o conflito, o resultado será denotado por $x \in X$, com as utilidades $u_A(x)$ para $A$ e $u_B(1-x)$ para $B$. Cada estado possui uma utilidade esperada da guerra dada por: $p_a u(1) + (1-p)u(0) - c_a$ para $A$ e uma fórmula similar para $B$, com custo $c_b$. Segundo o modelo de barganha de Rubinstein, com horizonte infinito onde as partes fazem ofertas alternadas e excluindo temporariamente a opção de guerra, o equilíbrio de Nash perfeito em sub-jogo (sem a opção de guerra) seria dado por $(x, 1-x)$, onde $x = \frac{1 -\delta_A}{1 - \delta_A \delta_B}$. A opção da guerra, no entanto, restringe os valores de $(x, 1-x)$ que são preferíveis à guerra, com $x > \mathbb{E}[u^g_A]$ e $1 - x > \mathbb{E}[u^g_B]$ para que a opção diplomática seja estritamente preferível para ambos.

A utilidade de estratégias complementares ou substitutas neste contexto torna-se evidente ao considerar diferentes cenários envolvendo grandes potências, potências médias e países pequenos. Por exemplo, em um cenário onde o estado $A$ é uma grande potência, a decisão sobre a alocação de recursos militares próximo à fronteira em conflito pode aumentar a sua probabilidade de vitória, influenciando assim as estratégias de negociação.

Em contraste, em um conflito sobre a expropriação de uma empresa estrangeira, como um setor de extração de petróleo, a presença de um aliado do país $B$ pode compelir o país $A$ a ceder mais na negociação para não prejudicar a aliança com o país $C$. Isso ilustra como estratégias em um jogo podem influenciar os resultados de outro.

# Pesquisa Empírica








<!-- The `\thanks` command may be used to create additional footnotes to the title or authors' names if required. Footnote symbols for this purpose should be used in the order -->
<!-- $^\ast$~(coded as `$^\ast$`), $\dagger$~(`$\dagger$`), $\ddagger$~(`$\ddagger$`), $\S$~(`$\S$`), $\P$~(`$\P$`), $\|$~(`$\|$`), -->
<!-- $\dagger\dagger$~(`$\dagger\dagger$`), $\ddagger\ddagger$~(`$\ddagger\ddagger$`), $\S\S$~(`$\S\S$`), $\P\P$~(`$\P\P$`). -->

# References


